version: '3'

services:
  rabbit:
    image: rabbitmq:3.7.8-management
    hostname: "rabbitmq"
    container_name: rabbit-dev
    restart: always
    volumes:
      - /dockervolume/rabbitmq/lib:/var/lib/rabbitmq
      - /dockervolume/rabbitmq/logs:/var/log/rabbitmq    
     
    ports:
      - 15672:15672
      - 5672:5672

    networks:
      - tcc-pos-net
    
networks:
  tcc-pos-net:
    name: tcc-pos-net
     